"""modify base_model

Revision ID: 7a8b3e6f0df7
Revises: f9c38c58ad05
Create Date: 2022-12-05 16:13:43.785106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a8b3e6f0df7'
down_revision = 'f9c38c58ad05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
